// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2FNYGsPhgbzPflnZybPtCBQFN5Slqoxw',
    appId: '1:1072815755569:web:5850d14a3427fe355de010',
    messagingSenderId: '1072815755569',
    projectId: 'explore-nauta',
    authDomain: 'explore-nauta.firebaseapp.com',
    storageBucket: 'explore-nauta.firebasestorage.app',
    measurementId: 'G-9XY5TK2R9N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5ZIEmlBmCuUGOAElAlsWZ3_teD7qlBrY',
    appId: '1:1072815755569:android:54f2cc247d5948e25de010',
    messagingSenderId: '1072815755569',
    projectId: 'explore-nauta',
    storageBucket: 'explore-nauta.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfvzXYPuY9n2qPQcrZDO1RNChIbYMBtIk',
    appId: '1:1072815755569:ios:2874c714ddc1d6505de010',
    messagingSenderId: '1072815755569',
    projectId: 'explore-nauta',
    storageBucket: 'explore-nauta.firebasestorage.app',
    iosBundleId: 'com.example.exploreNauta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfvzXYPuY9n2qPQcrZDO1RNChIbYMBtIk',
    appId: '1:1072815755569:ios:2874c714ddc1d6505de010',
    messagingSenderId: '1072815755569',
    projectId: 'explore-nauta',
    storageBucket: 'explore-nauta.firebasestorage.app',
    iosBundleId: 'com.example.exploreNauta',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2FNYGsPhgbzPflnZybPtCBQFN5Slqoxw',
    appId: '1:1072815755569:web:33ecd3dbb9200b235de010',
    messagingSenderId: '1072815755569',
    projectId: 'explore-nauta',
    authDomain: 'explore-nauta.firebaseapp.com',
    storageBucket: 'explore-nauta.firebasestorage.app',
    measurementId: 'G-4J6XVQNT6J',
  );
}
